[project]
name = "dotfiles-openjck-setup"
version = "1.0.0"
requires-python = ">=3.12"
dependencies = [
    "docopt==0.6.2",
]

[dependency-groups]
dev = [
    "black>=25.11.0",
    "flake8>=7.3.0",
    "isort>=7.0.0",
    "pyright>=1.1.407",
    "types-docopt>=0.6.11.20241107",
]

# Make isort and black agree on formatting of imports, so that they don't undo
# each other's work.
[tool.isort]
profile = "black"

[tool.pyright]
typeCheckingMode = "strict"
